package com.merrimackchat_client.gui;

import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mark Case
 */
public class Login extends javax.swing.JPanel {

    // Accessing HashMap keys
    HashMap<String,String> loginInfo = new HashMap<>();
             
    /**
     * Creates new form LoginBrowser
     * Default Constructor
     * @param loginOG
     */
    public Login(HashMap<String,String> loginOG) {

        initComponents();
        this.loginInfo = loginOG;

    }
    
    // Test variable for name
    public String test;
    
    // Getter methods for password and username
    public JPasswordField getPasswordText() {
        return passwordLoginField;
    }

    public JTextField getUsernameText2() {
        return usernameLoginField;
    }
    
    public void login() {
        usernameLoginField.grabFocus();
    }
    
    // Action listener for slide function
    public void addEventRegister(ActionListener event) {
        signUpButton.addActionListener(event);
    }
    
    // Getter and Setter field for test variable name
    public void setTest(String value) {
        this.test = value;
    }
    
    public String getTest() {
        return test;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new DesignPanels.PanelRound();
        usernameLoginLabel = new javax.swing.JLabel();
        passwordLoginLabel = new javax.swing.JLabel();
        usernameLoginField = new javax.swing.JTextField();
        passwordLoginField = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));

        usernameLoginLabel.setText("Username:");

        passwordLoginLabel.setText("Password:");

        loginLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 194, 7));
        loginLabel.setText("Login");

        signUpButton.setBackground(new java.awt.Color(255, 255, 255));
        signUpButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 194, 7));
        signUpButton.setText("No account? Sign up here");
        signUpButton.setBorder(null);
        signUpButton.setBorderPainted(false);
        signUpButton.setContentAreaFilled(false);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(signUpButton)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(usernameLoginLabel)
                            .addGap(18, 18, 18)
                            .addComponent(usernameLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addComponent(passwordLoginLabel)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(loginLabel))
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(passwordLoginField))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLoginLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLoginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLoginLabel))
                .addGap(18, 18, 18)
                .addComponent(signUpButton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginLabel;
    private DesignPanels.PanelRound loginPanel;
    private javax.swing.JPasswordField passwordLoginField;
    private javax.swing.JLabel passwordLoginLabel;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField usernameLoginField;
    private javax.swing.JLabel usernameLoginLabel;
    // End of variables declaration//GEN-END:variables

}
