package com.merrimackchat_client.gui;

import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


/**
 *
 * @author Mark Case
 */
public class Register extends javax.swing.JPanel {

 
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    
    public void register() {
        registerUsername.grabFocus();
    }
    
    // Action listener for slide function
    public void addEventBackLogin(ActionListener event) {
        backToLoginBtn.addActionListener(event);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new DesignPanels.PanelRound();
        usernameLbl2 = new javax.swing.JLabel();
        PasswordLbl2 = new javax.swing.JLabel();
        registerUsername = new javax.swing.JTextField();
        registerPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        backToLoginBtn = new javax.swing.JButton();

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setForeground(new java.awt.Color(255, 255, 255));
        panelRound3.setPreferredSize(new java.awt.Dimension(238, 163));

        usernameLbl2.setText("Username:");

        PasswordLbl2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 194, 7));
        jLabel3.setText("Register");

        backToLoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        backToLoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backToLoginBtn.setForeground(new java.awt.Color(255, 194, 7));
        backToLoginBtn.setText("Back to Login");
        backToLoginBtn.setBorder(null);
        backToLoginBtn.setBorderPainted(false);
        backToLoginBtn.setContentAreaFilled(false);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLbl2)
                            .addComponent(PasswordLbl2))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(registerPassword)))
                    .addGroup(panelRound3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backToLoginBtn)
                            .addComponent(jLabel3))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLbl2))
                .addGap(18, 18, 18)
                .addComponent(backToLoginBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Getter and Setters for button and textfields
    public JButton getBackToLoginBtn() {
        return backToLoginBtn;
    }

    public JTextField getRegisterUsername() {
        return registerUsername;
    }

    public JPasswordField getRegisterPassword() {
        return registerPassword;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLbl2;
    private javax.swing.JButton backToLoginBtn;
    private javax.swing.JLabel jLabel3;
    private DesignPanels.PanelRound panelRound3;
    private javax.swing.JPasswordField registerPassword;
    private javax.swing.JTextField registerUsername;
    private javax.swing.JLabel usernameLbl2;
    // End of variables declaration//GEN-END:variables
}
